### ISSUE TITLE
helm_driver是该怎么设置？

### ISSUE THREAD

**Issue by zhaoxianhua** [opskumu/helm-wrapper#10]
请问代码中helm_driver是该怎么设置？
还有运行时抛出Kubernetes cluster unreachable: CreateFile config : Thesystem cannot find th file specified，求大佬指点。

**Comment by opskumu** [comment]
`--kubeconfig` 默认如果你不指定的话，使用默认的路径，一般是 ~/.kube/config。这个配置是必须的

确保你配置了正确的 kubeconfig，如果 kubeconfig 没有配置或者配置错误，那么集群就访问不了
