### ISSUE TITLE
helm show

### ISSUE THREAD

**Issue by stupid-yu** [opskumu/helm-wrapper#103]
Hello, is there any plan to implement this interface `helm show all [CHART] [flags]`

for example

`helm show all helm-wrapper --repo repo-url --username admin --password admin --version 0.1.0`

![images](https://github.com/opskumu/helm-wrapper/assets/52521933/b91daffe-54dd-438a-99d0-847204effa3e)

**Comment by opskumu** [comment]
already support, use like:

+ helm show
    - `GET`
    - `/api/charts`

| Params | Description |
| :--- | :--- |
| chart  | chart name, required|
| info   | support all/readme/values/chart, default all |
| version | --version |

**Comment by stupid-yu** [comment]
Thx, I've solved my problem.

Here is my temporary solution.

![image](https://github.com/opskumu/helm-wrapper/assets/52521933/3d7122b0-edaa-41e0-974a-bfbf1f43077d)
