### ISSUE TITLE
Getting "context deadline exceeded" error when using "wait:True"

### ISSUE THREAD

**Issue by jasseeeem** [opskumu/helm-wrapper#104]
I'm attempting to sequentially patch deployments within my cluster, waiting for each deployment to reach the READY state before moving to the next. I added the 'wait' flag in the body for this purpose, but I'm encountering the following error in the process: `client rate limiter wait returned an error: context deadline exceeded`

How to fix this issue?

Related issue: https://github.com/opskumu/helm-wrapper/issues/66

**Comment by opskumu** [comment]
When setting wait, it will wait for as long as --timeout, helm default timeout 5m0s, helm-wrapper without set default time. a temporary solution, you can set it timeout, and I will fix it.

**Comment by jasseeeem** [comment]
Thank you @opskumu. Updating the `helm-wrapper` version from `1.0.0` to `1.0.2` fixed the issue.
