### ISSUE TITLE
在K8S pod里启动不了，请问是为什么呢？

### ISSUE THREAD

**Issue by winnie-cell** [opskumu/helm-wrapper#11]
![image](https://user-images.githubusercontent.com/69226247/92551947-061e0880-f292-11ea-8879-15102a5d6791.png)

**Comment by opskumu** [comment]
确认给的资源是否足够，Killed 一般是 OOM 导致的

**Comment by winnie-cell** [comment]
> 确认给的资源是否足够，Killed 一般是 OOM 导致的

我多给些资源先试一下，一般需要多少资源呢？

**Comment by opskumu** [comment]
本身也不消耗什么资源，你给个 100M 看看，基本上是这种情况，Killed 一般都是资源不足导致的

**Comment by winnie-cell** [comment]
> 本身也不消耗什么资源，你给个 100M 看看，基本上是这种情况，Killed 一般都是资源不足导致的

好的 已经好了，谢谢。

**Comment by opskumu** [comment]
> > 本身也不消耗什么资源，你给个 100M 看看，基本上是这种情况，Killed 一般都是资源不足导致的
> 
> 好的 已经好了，谢谢。

客气的
