### ISSUE TITLE
接口namespace参数没完全生效

### ISSUE THREAD

**Issue by donhac** [opskumu/helm-wrapper#2]
env：
k8s version: 1.15.5
helm version: 3.2.3

接口调用helm-wrapper时，指定命名空间只对release生效，并未对chart包里的deployment和service等资源生效（yaml文件未指定命名空间），比如接口调用传参test命名空间，release会在test创建，但相应的chart里的其他资源还是在default命名空间下:
`POST http://localhost:31021/api/namespaces/test/releases/demo-apm`

在集群内直接使用helm命令指定namespace的话，release和相应集群资源均会在对应命名空间内创建：
`helm install demo-apm ./apm-server-2.1.5.tgz --namespace=test`

**Comment by opskumu** [comment]
嗯，已经确认了，稍晚些时候我修复下

**Comment by opskumu** [comment]
@donhac 最新代码已经修复，感谢反馈 ：）
