### ISSUE TITLE
Support multiple cluster deployment the Helm charts

### ISSUE THREAD

**Issue by Aisuko** [opskumu/helm-wrapper#20]
Hi @opskumu , big thanks for your work on this amazing project. And also I know the best situation for the repo is use to one cluster, because we all know that the helm with `init` command with an necessary `kubeconfig`. 

But if there another situation is that we want to support for the multiple cluster. how should we do?

~~* Should we `init` with all the cluster `kubeconfig`?~~
  * In fact, that can be easy to implement, but there may have a another issue is that 

~~* How we should clarify the multiple cluster?~~ 
  * I have a solution may we can use the `kubeconfig context` to clarify the different cluster.

~~* If we want to add new cluster, all should we add the new cluster configuration into the `helm-wrapper`?~~
  * Oh, may be we can restart the pods

* Should we add the parameter `cluster configuration context` into the APIs? The user may want to deploy to different cluster

Yep, I answer myself

**Comment by opskumu** [comment]
Thanks, for multiple cluster maybe we can write a simple http proxy, config like:

```
cluster:
    - name: "test-1"
       url: "<helm-wrapper-test-1>"
    - name: "test-2"
       url: "<helm-wrapper-test-2>"
```

with http://<proxy-url>/test-1/<path> or http://<proxy-rul>/test-2/<path> deploy to correct cluster.

**Comment by Aisuko** [comment]
Cloud we make a little change that we can only use the `cluster context` may be like 

```
{
    "dry_run": false,           // `--dry-run`
    "disable_hooks": false,     // `--no-hooks`
    "wait": false,              // `--wait`
    "devel": false,             // `--false`
    "description": "",          // `--description`
    "atomic": false,            // `--atomic`
    "skip_crds": false,         // `--skip-crds`
    "sub_notes": false,         // `--render-subchart-notes`
    "create_namespace": false,  // `--create-namespace`
    "dependency_update": false, // `--dependency-update`
    "values": "",               // `--values`
    "set": [],                  // `--set`
    "set_string": []            // `--set-string`
    "context" : xxxxxxx   //  `--the cluster context`
}
```

**Comment by Aisuko** [comment]
> thanks, let me think.

I can as a contributor we can work together. But we should figure out the change(with a little change and  more powerful for using) first.

**Comment by opskumu** [comment]
Ok, You can add context option

**Comment by opskumu** [comment]
#21
