### ISSUE TITLE
请问，用户如何在线查看并修改chart包的信息呢？

### ISSUE THREAD

**Issue by DuckStarBall** [opskumu/helm-wrapper#23]
我们的包放在某一路径下，用户通过rest接口可以查看chart包的配置信息，那么如何用户如果想修改呢？目前好像是不支持修改的吧？我觉得这个需求貌似更实际一点，用户想安装某一个应用，但是发现这个chart包有一些配置是需要修改的，然后调用接口进行修改，修改完成之后进行部署，是不是更接近实际的应用情况？

**Comment by opskumu** [comment]
helm-wrapper 定位是 helm 本身的上层 API 封装，不涉及到 helm charts 本身的管理和维护

**Comment by DuckStarBall** [comment]
好的，多谢
