### ISSUE TITLE
以info=values这种查询chart包信息时，values返回的是string，可读性很差？可否优化一下，怎么优化呢？

### ISSUE THREAD

**Issue by DuckStarBall** [opskumu/helm-wrapper#24]
当我们查询chart包的信息时，返回的为一个字符串，而且可读性很差，怎么完善一下呢？结果如下：
"data": "# Default values for test.\n# This is a YAML-formatted file.\n# Declare variables to be passed into your templates.\n\nreplicaCount: 1\n\nimage:\n  repository: nginx\n  pullPolicy: IfNotPresent\n  # Overrides the image tag whose default is the chart appVersion.\n  tag: \"\"\n\nimagePullSecrets: []\nnameOverride: \"\"\nfullnameOverride: \"\"\n\nserviceAccount:\n  # Specifies whether a service account should be created\n  create: true\n  # Annotations to add to the service account\n  annotations: {}\n  # The name of the service account to use.\n  # If not set and create is true, a name is generated using the fullname template\n  name: \"\"\n\npodAnnotations: {}\n\npodSecurityContext: {}\n  # fsGroup: 2000\n\nsecurityContext: {}\n  # capabilities:\n  #   drop:\n  #   - ALL\n  # readOnlyRootFilesystem: true\n  # runAsNonRoot: true\n  # runAsUser: 1000\n\nservice:\n  type: NodePort\n  port: 80\n\ningress:\n  enabled: false\n  annotations: {}\n    # kubernetes.io/ingress.class: nginx\n    # kubernetes.io/tls-acme: \"true\"\n  hosts:\n    - host: chart-example.local\n      paths: []\n  tls: []\n  #  - secretName: chart-example-tls\n  #    hosts:\n  #      - chart-example.local\n\nresources: {}\n  # We usually recommend not to specify default resources and to leave this as a conscious\n  # choice for the user. This also increases chances charts run on environments with little\n  # resources, such as Minikube. If you do want to specify resources, uncomment the following\n  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.\n  # limits:\n  #   cpu: 100m\n  #   memory: 128Mi\n  # requests:\n  #   cpu: 100m\n  #   memory: 128Mi\n\nautoscaling:\n  enabled: false\n  minReplicas: 1\n  maxReplicas: 1000\n  targetCPUUtilizationPercentage: 80\n  # targetMemoryUtilizationPercentage: 80\n\nnodeSelector: {}\n\ntolerations: []\n\naffinity: {}\n"

请问可以完善成JSON格式的吗？

**Comment by opskumu** [comment]
我这边试试看效果

**Comment by DuckStarBall** [comment]
如果是json格式的，是不是就会好很多？



---原始邮件---
发件人: "Kumu"<notifications@github.com&gt;
发送时间: 2020年11月11日(周三) 晚上8:15
收件人: "opskumu/helm-wrapper"<helm-wrapper@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"JingStar"<593778746@qq.com&gt;;
主题: Re: [opskumu/helm-wrapper] 以info=values这种查询chart包信息时，values返回的是string，可读性很差？可否优化一下，怎么优化呢？ (#24)




 
我这边试试看效果

**Comment by DuckStarBall** [comment]
@opskumu 请问您这边有什么好的处理方案吗？

**Comment by opskumu** [comment]
还没来得及看，最近有点忙 ；）

**Comment by opskumu** [comment]
@DuckStarBall 刚刚看了一下，不是很好处理，之前显示这类数据统一让前端处理的，调 API 查看确实不太友好，我再看看怎么处理吧

**Comment by DuckStarBall** [comment]
这个确实有点恼火，但是真实用的话返回这个信息确实不友好，基本没有可读性，还是需要处理一下，可能还有点复杂。



---原始邮件---
发件人: "Kumu"<notifications@github.com&gt;
发送时间: 2020年11月12日(周四) 晚上10:19
收件人: "opskumu/helm-wrapper"<helm-wrapper@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"JingStar"<593778746@qq.com&gt;;
主题: Re: [opskumu/helm-wrapper] 以info=values这种查询chart包信息时，values返回的是string，可读性很差？可否优化一下，怎么优化呢？ (#24)




 
@DuckStarBall 刚刚看了一下，不是很好处理，之前显示这类数据统一让前端处理的，调 API 查看确实不太友好，我再看看怎么处理吧

**Comment by opskumu** [comment]
@DuckStarBall 嗯，这个和 helm 命令行还不一样，helm 本身是直接 print 出来的，所以看到的 \n 都是转义成换行的

**Comment by DuckStarBall** [comment]
嗯嗯，转成json应该可行，但是需要思考一下，如果直接对yaml处理的话，还可以用json包，但是这个字符串的话也没有办法用包处理，有点恼火，思考思考，这个showChart确实需要改一下，都思考一下



---原始邮件---
发件人: "Kumu"<notifications@github.com&gt;
发送时间: 2020年11月12日(周四) 晚上10:44
收件人: "opskumu/helm-wrapper"<helm-wrapper@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"JingStar"<593778746@qq.com&gt;;
主题: Re: [opskumu/helm-wrapper] 以info=values这种查询chart包信息时，values返回的是string，可读性很差？可否优化一下，怎么优化呢？ (#24)




 
@DuckStarBall 嗯，这个和 helm 命令行还不一样，helm 本身是直接 print 出来的，所以看到的 \n 都是转义成换行的
