### ISSUE TITLE
调用helm get 接口，info=values时，我看返回值给格式化为json了，是否可以通过配置参数返回原来的yaml字符串？

### ISSUE THREAD

**Issue by singeleaf** [opskumu/helm-wrapper#26]
我这边想得到其yaml字符串，在界面通过文本框显示出来，用户直接修改yaml文本完成配置，现在格式化为json后，我还得转换为yaml文本，因为我看底层本来也是yaml字符串。

**Comment by singeleaf** [comment]
是否可以参考kubectl输出的方式，自定义输出格式

kubectl get pod guestbook-9dcc486d8-2prlr -o json  
返回json格式

kubectl get pod guestbook-9dcc486d8-2prlr -o yaml
返回yaml格式

**Comment by opskumu** [comment]
返回的 values 值是字符串，内容还是 yaml 原格式呢，前端界面格式化一下换行应该就可以正常显示了

**Comment by singeleaf** [comment]
我说的是这个接口哈：/api/namespaces/default/releases/g3?info=values

返回值：
{
    "code": 0,
    "data": {
        "replicaCount": 1,
        "service": {
            "port": 3000,
            "type": "LoadBalancer"
        }
    }
}

刚刚拉的master最新的代码，不是helm show这个接口，是helm get这个接口

**Comment by opskumu** [comment]
明白了，这个我看看好解决不

**Comment by opskumu** [comment]
@singeleaf 最新 master 已经支持，通过 `output` 选项支持，默认 json，可以赋值 yaml

![image](https://user-images.githubusercontent.com/5445356/99361568-4088cf00-28ed-11eb-9ac5-dd4ed676818c.png)

有问题反馈

**Comment by opskumu** [comment]
issue 先关闭了，如果同样的问题你可以 reopen 一下

**Comment by singeleaf** [comment]
已经可以了，感谢支持
