### ISSUE TITLE
没有安装/更新 指定版本的功能么?

### ISSUE THREAD

**Issue by 251745291** [opskumu/helm-wrapper#28]
安裝接口 helm install  的参数列表 中没有 version  
如果要指定版本安装 实现 helm install test-my-name chartmuseum/test --version 0.1.0
的效果要如何做呢?

**Comment by opskumu** [comment]
嗯，这个没有支持，我支持了下。你 pull 下最新代码，已支持自定义指定 version 参数

**Comment by 251745291** [comment]
试了 可以了 ~  3Q ~~
