### ISSUE TITLE
Is this GPL?

### ISSUE THREAD

**Issue by lkusnadi** [opskumu/helm-wrapper#3]
Hi Kumu,
Just wondering if you can let me know if this is GPL? 
I'm doing integration work, for the company I'm working for. I'm not using your helm-wrapper to build commercial solution.
Thanks.

**Comment by opskumu** [comment]
@lkusnadi helm-wrapper is GPL, you can do you want to do.

**Comment by lkusnadi** [comment]
> @lkusnadi helm-wrapper is GPL, enjoy : ）

Thank you
