### ISSUE TITLE
上传chart目录是否直接放到仓库下，这样listchart就能拿到全部的chart。现在上传和仓库的是分开的。

### ISSUE THREAD

**Issue by zhaoxianhua** [opskumu/helm-wrapper#30]

**Comment by opskumu** [comment]
helm-wrapper 本身是遵循 helm commond 来操作的，当时做上传的功能还是偏临时使用场景使用的。如果要结合 chart repo 的话，不同的 repo 调用 API 也是不一样的，还是希望 helm-wrapper 本身纯粹一点。不知道有没有理解错你的意思
