### ISSUE TITLE
关于rollback接口对多参数的支持，望考虑

### ISSUE THREAD

**Issue by RandyWithZero** [opskumu/helm-wrapper#32]
比如--recreate-pods,--force --cleanup-on-fail
对应代码
client := action.NewRollback(actionConfig)
	client.Version = reversion
	//todo 多参数支持
	//client.Force=true
helm/v3...下的结构体参数可以对接上
type Rollback struct {
	cfg *Configuration

	Version       int
	Timeout       time.Duration
	Wait          bool
	DisableHooks  bool
	DryRun        bool
	Recreate      bool // will (if true) recreate pods after a rollback.
	Force         bool // will (if true) force resource upgrade through uninstall/recreate if needed
	CleanupOnFail bool
	MaxHistory    int // MaxHistory limits the maximum number of revisions saved per release
}

**Comment by opskumu** [comment]
好的 我这块看下

**Comment by opskumu** [comment]
@RandyWithZero 已经添加支持
