### ISSUE TITLE
支持https吗？

### ISSUE THREAD

**Issue by koulq** [opskumu/helm-wrapper#33]
之前使用helm3.5客户端，配置apiServer地址和token，使用https协议，发现没法使用，不知道咱们的sdk对这一块有木有改进

**Comment by opskumu** [comment]
@koulq 具体可以描述下吗，一般是直接通过 kubeConfig 配置的，https 是没有问题的

**Comment by koulq** [comment]
我在k8s集群本地，也就是master节点上执行命令是没问题的
![image](https://user-images.githubusercontent.com/18571340/105473035-96a43500-5cd7-11eb-9f37-df22001e0c67.png)
但是我在远程执行命令报错
![image](https://user-images.githubusercontent.com/18571340/105473169-c0f5f280-5cd7-11eb-9ccc-5de43404a939.png)

**Comment by opskumu** [comment]
@koulq 你说的是 helm 本身，helm 本身建议你去 https://github.com/helm/helm 咨询相关问题哦
