### ISSUE TITLE
post 方式调用install接口时，http的body体参数无法获取

### ISSUE THREAD

**Issue by bainilybi** [opskumu/helm-wrapper#34]
请教一个问题，我在调用 /api/namespaces/:namespace/releases/:release?chart=<chartName>
这个接口时，body里的参数虽然提交了，但是在releases.go的installRelease涵数里处理的时候，经过：
	var options releaseOptions
	err := c.ShouldBindJSON(&options)
	if err != nil && err != io.EOF {
		respErr(c, err)
		return
	}
处理完后，options里面的变量还是空的。转json，没有解析到值。请求是哪儿的原因呢？

例如，请求体是：
{
    "version": "0.0.3"
}

通过下面的方式，是能打印出来body的：
	buf := make([]byte, 1024000)
	n, _ := c.Request.Body.Read(buf)
	fmt.Println(string(buf[0:n]))

谢谢啦！

**Comment by opskumu** [comment]
问题已经确认，最新版已修复
