### ISSUE TITLE
关于chart版本的问题

### ISSUE THREAD

**Issue by bainilybi** [opskumu/helm-wrapper#35]
项目里，对chart的版本有限制。必须是满足一定规范的Chart版本号才行。我觉得，对于版本号的长度和形式，不必做过多限制，以体现包容性。例如，1.0.0-132421234-1604475612345-1111  这样的版本号也应是允许的。

**Comment by opskumu** [comment]
版本号貌似没有限制吧，本身都是集成 Helm SDK 的，helm-wrapper 本身没有做这些限制的

**Comment by bainilybi** [comment]
在repositories.go类里面：177~179行，还有75行的len(version) > 0，都会限制版本号。如果harbor里的chart版本比较长，这样的Chart，通过接口就list不出来。

**Comment by opskumu** [comment]
默认是 stable 的，helm-wrapper 只是使用了一个默认值，你可以根据需求传递，具体可以见 helm 自身的代码：

https://github.com/helm/helm/blob/master/cmd/helm/search_repo.go#L129-L143

https://github.com/helm/helm/blob/85794cfc6eb7216c987f544ceb871c94dbec6a7f/cmd/helm/search_repo.go#L176-L197

**Comment by opskumu** [comment]
你可以传递 version 值覆盖默认的 stable 值
