### ISSUE TITLE
是否可以整理一个官方的Chart

### ISSUE THREAD

**Issue by bainilybi** [opskumu/helm-wrapper#36]
目前是几个yaml文件，是否方便提供一个官方Chart？以统一大家的使用。谢谢～

**Comment by opskumu** [comment]
> 目前是几个yaml文件，是否方便提供一个官方Chart？以统一大家的使用。谢谢～

你是指 helm-wrapper 本身支持 helm 安装吗？如果是的话后面有时间我弄一下哈

**Comment by bainilybi** [comment]
是helm-wrapper本身的Chart。谢谢啦～
