### ISSUE TITLE
对helm install或者update接口返回内容的建议

### ISSUE THREAD

**Issue by bainilybi** [opskumu/helm-wrapper#37]
对这两个接口，是否有必要将REVISION、STATUS等信息也返回出来。这样，可以将信息存储，自己能知道这个服务是否有历史记录可以回滚。否则，只能list的时候，才知道REVISION。

**Comment by opskumu** [comment]
本身操作都是基于 helm Go SDK 的，大部分还是兼容相关命令的返回，不会添加非原生命令返回的额外信息哦，偏纯粹的上层封装

**Comment by bainilybi** [comment]
明白，谢谢！
