### ISSUE TITLE
使用私有的harbor仓库，https的url配置会报错

### ISSUE THREAD

**Issue by fomin-zhu** [opskumu/helm-wrapper#38]
使用https://{ip地址}/chartrepo/abc，自签的https证书，提示下面的错误，
x509:certificate signed by unknown authority
使用helm repo add是没有问题的，是需要传递--ca-file吗？

**Comment by opskumu** [comment]
> 使用https://{ip地址}/chartrepo/abc，自签的https证书，提示下面的错误，
> x509:certificate signed by unknown authority
> 使用helm repo add是没有问题的，是需要传递--ca-file吗？

好的，我这边确认一下
