### ISSUE TITLE
在配置文件中设置跳过harbor认证 ，获取chart详情时，这个跳过没起作用

### ISSUE THREAD

**Issue by bainilybi** [opskumu/helm-wrapper#39]
在config.yaml里增加insecure_skip_tls_verify: true
在/api/charts接口时，或者install的时候，这个跳过没起作用。

**Comment by opskumu** [comment]
@bainilybi  看了下，config 中 `insecure_skip_tls_verify:true` 主要是初始化 repo 的时候使用，chart 升级和安装的时候需要额外传入定义这个值，默认是 false 的

**Comment by bainilybi** [comment]
明白，谢谢～
