### ISSUE TITLE
无法通过api进行helm install

### ISSUE THREAD

**Issue by RandyWithZero** [opskumu/helm-wrapper#40]
不能正常的调用install api，总是报错  "error": "failed to download \"helloworld\" (hint: running `helm repo update` may help)"
命令可以安装
`[root@kube-master1 ~]# helm install aa helloworld --repo http://10.10.82.80/chartrepo/library --version 0.1.0
NAME: aa
LAST DEPLOYED: Wed Jul 21 02:47:40 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=helloworld,app.kubernetes.io/instance=aa" -o jsonpath="{.items[0].metadata.name}")
  export CONTAINER_PORT=$(kubectl get pod --namespace default $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace default port-forward $POD_NAME 8080:$CONTAINER_PORT`
![图片](https://user-images.githubusercontent.com/38777687/126444657-ef995f46-63c0-4676-90d8-5fe275cec753.png)
![图片](https://user-images.githubusercontent.com/38777687/126444711-56150dc8-0bac-4879-abdb-43875ab9369a.png)
请问是什么原因，谢谢！

**Comment by opskumu** [comment]
@RandyWithZero 确认下 helloworld 这个 chart 是否真的存在，正常的格式如 <repoName>/<chartName>

**Comment by RandyWithZero** [comment]
@opskumu 通过命令行所指的参数和api调用的参数是一致的，api的参数不是对应命令行参数的吗》 如repo--> --repo

**Comment by RandyWithZero** [comment]
@opskumu 
![图片](https://user-images.githubusercontent.com/38777687/126452718-e02f3f6c-094e-40da-9ead-cb9bab659a35.png)
![图片](https://user-images.githubusercontent.com/38777687/126452797-01504089-01ed-418b-9e8f-7bedcf489f36.png)
这是使用您最新版本的helm api服务的接口调用情况，第二张图是我在helm api服务容器中curl的结果
