### ISSUE TITLE
查看chart信息支持url的

### ISSUE THREAD

**Issue by RandyWithZero** [opskumu/helm-wrapper#42]
@opskumu 你好，请问现在支持命令 helm show values  http://10.10.10.100/chartrepo/library/charts/helloworld-0.1.0.tgz这种api,目前看api/charts？chart=xx接口是针对uploadPath/下的chart包的擦看信息
helm show 
This command inspects a chart (directory, file, or URL)

**Comment by opskumu** [comment]
@RandyWithZero 

![image](https://user-images.githubusercontent.com/5445356/130041081-2d8ced57-d044-43a9-a6b4-9a62e9eaef20.png)

支持的哈

**Comment by RandyWithZero** [comment]
本地换成文件测试时可以的，但是url的不行
![图片](https://user-images.githubusercontent.com/38777687/130041830-54538265-ef1e-4f68-8529-be2c43c65b57.png)

**Comment by opskumu** [comment]
@RandyWithZero 直接写 chart 名字就好了，不要加 tgz 哈

**Comment by RandyWithZero** [comment]
看代码是会在uploadPath那个目录找chart名字对应的包，但前提得在uploadPath现有这个包才能解析成功，url的一样，所示出现上面的提示，显然我是没有这么一个叫http...的包的，是希望获取url的数据进行解析
![图片](https://user-images.githubusercontent.com/38777687/130043132-9743bca5-cf9a-45d7-8d6c-4196b2bc2ed3.png)

**Comment by RandyWithZero** [comment]
我通过修改了参数接收，也是这样的
![图片](https://user-images.githubusercontent.com/38777687/130048655-4b5ee368-be1f-49fa-8c19-d87f42c6dc6c.png)

**Comment by opskumu** [comment]
这个应该 download 失败了吧，不在 repo 里面这个我没有试过，晚点我确认下哈

**Comment by opskumu** [comment]
@RandyWithZero 问题已经修复了哈，支持远程 helm show 了
