### ISSUE TITLE
Helm-wrapper as external package

### ISSUE THREAD

**Issue by moriyahazan** [opskumu/helm-wrapper#44]
I want to include this repo as a dependency on another Go application. Because I have to expand the capability of APIs
I added this line:
`	import "github.com/opskumu/helm-wrapper"
`
the package is loaded. But I haven't an option call to an inner method like `installRelease` since all methods are not exported 
Any idea how can I achieve this requirement without fork the project?

**Comment by opskumu** [comment]
> I want to include this repo as a dependency on another Go application. Because I have to expand the capability of APIs I added this line: ` import "github.com/opskumu/helm-wrapper" ` the package is loaded. But I haven't an option call to an inner method like `installRelease` since all methods are not exported Any idea how can I achieve this requirement without fork the project?

https://golang.org/doc/effective_go#names Names are as important in Go as in any other language. They even have semantic effect: the visibility of a name outside a package is determined by whether its first character is upper case.
