### ISSUE TITLE
Help Chart to deploy the Helm Wrapper

### ISSUE THREAD

**Issue by anton-johansson** [opskumu/helm-wrapper#47]
Is there possibly a Helm Chart that can be used to deploy the Helm Wrapper? :sunglasses:

**Comment by opskumu** [comment]
good idea, i will try to write a helm chart

**Comment by wibed** [comment]
@opskumu i am curious, what is the status of this?

**Comment by opskumu** [comment]
@wibed https://github.com/opskumu/helm-wrapper/tree/master/helm-wrapper here

**Comment by wibed** [comment]
@opskumu thank you ! 
/close
