### ISSUE TITLE
The values option

### ISSUE THREAD

**Issue by anton-johansson** [opskumu/helm-wrapper#48]
Hi! I'm planning on using this tool for our automation process, it looks very promising! I just have one question regarding the `values` option. Using `helm` CLI, `--values` is the path to a YAML file. I'm assuming the `values` option here is the actual YAML?

I have quite complex YAML files and it would simplify a lot if I could use that. :+1:

**Comment by opskumu** [comment]
> Hi! I'm planning on using this tool for our automation process, it looks very promising! I just have one question regarding the `values` option. Using `helm` CLI, `--values` is the path to a YAML file. I'm assuming the `values` option here is the actual YAML?
> 
> I have quite complex YAML files and it would simplify a lot if I could use that. 👍

Hi, helm-wrapper `values` need YAML file content, a string type

**Comment by anton-johansson** [comment]
Great, thanks for the quick answer! :partying_face:
