### ISSUE TITLE
参数values不支持文件形式的吗

### ISSUE THREAD

**Issue by newbietk** [opskumu/helm-wrapper#52]

**Comment by opskumu** [comment]
不支持哦

**Comment by newbietk** [comment]
用helm --values是可以直接指定文件的，这块helmwrapper只能是内容是吧

**Comment by opskumu** [comment]
@newbietk 对的，这块主要是为了 API 远程调用，直接以内容的方式发送的

**Comment by zhangzimao** [comment]
values可以支持url吗 ，原生的还支持url哦

**Comment by opskumu** [comment]
@zhangzimao url 这个我考虑支持下哈，需要稍微晚点

**Comment by opskumu** [comment]
@zhangzimao 最新版已支持 url 方式
