### ISSUE TITLE
what should I add in config.yaml

### ISSUE THREAD

**Issue by pallasathena92** [opskumu/helm-wrapper#58]
would you give me a more detailed description of config.yaml for helm-wrapper? what is the purpose?
and also for this command ` ./helm-wrapper --config </path/to/config.yaml> --kubeconfig </path/to/kubeconfig>`, where should I run it? I get error when I run at ~ or ~/hlem-wrapper or ~/hlem-wrapper/helm-wrapper, I all get error " ./helm-wrapper: is a directory"

**Comment by opskumu** [comment]
@pallasathena92 helm-wrapper need make build, default  helm-wrapper binary in helm-wrapper/bin/ dir

`config.yaml` like:

```
helmRepos:
  - name:<helmRepoName>
    url: <helmRepoUrl>
```

**Comment by pallasathena92** [comment]
the helmRepo is the repo for the helm-wrapper or the application which will use the helm-wrapper?

**Comment by pallasathena92** [comment]
btw, I have default helm-wrapper binary in helm-wrapper/bin/ and when I tried to run ./helm-wrapper command, the error message like, "this is a binary can't run it"

**Comment by opskumu** [comment]
> the helmRepo is the repo for the helm-wrapper or the application which will use the helm-wrapper?

Yes

**Comment by opskumu** [comment]
> btw, I have default helm-wrapper binary in helm-wrapper/bin/ and when I tried to run ./helm-wrapper command, the error message like, "this is a binary can't run it"

check the binary permission, need have`x` perm, like `0755`

**Comment by pallasathena92** [comment]
thanks, will close it
