### ISSUE TITLE
helm uninstall 接口有一个问题

### ISSUE THREAD

**Issue by 600849155** [opskumu/helm-wrapper#7]
执行 helm uninstall 接口 卸载如下状态的 jjj、jj1j 应用时，会返回异常：uninstallation completed with 1 error(s): uninstall: Failed to purge the release: release: not found
<img width="689" alt="微信截图_20200806112929" src="https://user-images.githubusercontent.com/20468753/89503244-dc884200-d7f8-11ea-8be0-454cf4379744.png">

**Comment by opskumu** [comment]
好的，我这边确认下

**Comment by opskumu** [comment]
@600849155 直接用 helm 就可以删除吗？

**Comment by 600849155** [comment]
> @600849155 直接用 helm 就可以删除吗？

直接用 helm uninstall 命令是可以删除的

**Comment by opskumu** [comment]
好的 我这边再排查一下

**Comment by opskumu** [comment]
![image](https://user-images.githubusercontent.com/5445356/89603126-f37f7080-d89a-11ea-86e4-02b91897ca50.png)

![image](https://user-images.githubusercontent.com/5445356/89603109-e95d7200-d89a-11ea-84d5-e14a7199dd54.png)


本地实际测试没有出现你描述的情况哦，确认调用 API 指定的是正确的命名空间吗

**Comment by 600849155** [comment]
我现在也复现不了这个偶发问题，能够确保调用 api 指定的命名空间是正确的，helm 版本也的确是 V3 版本，有可能是 helm 的问题

**Comment by opskumu** [comment]
> 我现在也复现不了这个偶发问题，能够确保调用 api 指定的命名空间是正确的，helm 版本也的确是 V3 版本，有可能是 helm 的问题

好的，感谢反馈，后续我这边也继续观察下

**Comment by opskumu** [comment]
问题暂时先关闭了，如果复现再开启
