### ISSUE TITLE
启动程序出现DownloadIndexFile()失败

### ISSUE THREAD

**Issue by dnsisme** [opskumu/helm-wrapper#71]
下载源码后，直接在k8s集群下编译通过，启动二进制文件，调用initRepos失败，initRepos()中DownloadIndexFile返回错误。

问题一：本地无法直接查看DownloadIndexFile()方法的定义，只能去官网查看。

想知道直接拿到源码，需要做哪些更改，就可以在自己的集群正常运行，准备用来做远程自动化部署更新服务。

**Comment by opskumu** [comment]
@dnsisme 可以直接正常运行的，不需要做特别的变更，initRepos 有问题应该是对应 repo 的问题吧，是用的私有的还是公共的啊

**Comment by opskumu** [comment]
```
helmRepos:
  - name: <repo名>
    url: <repo地址>
```

**Comment by dnsisme** [comment]
我们使用的是私有镜像仓库，私有镜像仓库的地址入口是：https://iregistry.baidu-int.com/

下面是直接使用helm install <service-name> -n namespace ./home/work/middle/mongodb部署的chart管理的mongo中镜像仓库以及仓库名称的配置

![image](https://user-images.githubusercontent.com/88881577/183901460-9dd2919f-3925-4f37-8df2-e96edbe90bd2.png)

下面是程序启动方式，启动报错以及config配置信息
![image](https://user-images.githubusercontent.com/88881577/183901129-8212172b-afb6-4d4e-aaa8-7ae53195b681.png)

<img width="796" alt="image" src="https://user-images.githubusercontent.com/88881577/183897645-7c291faf-8441-428e-a2c6-6c6ba4c332ca.png">

**Comment by opskumu** [comment]
@dnsisme 好的，我确认下哈

**Comment by opskumu** [comment]
@dnsisme 直接 helm 添加 repo 和部署是可以的吗，方便截图吗？另外直接试一下公共仓库是不是支持的

**Comment by opskumu** [comment]
@dnsisme 你这块看着是下载 helm index 文件的时候直接抛错了

**Comment by dnsisme** [comment]
@opskumu 您好 我这边直接helm repo add 没问题，与此同时测试helm repo add 添加公共仓库和加载公共镜像仓库配置没问题，更新config.yaml为helm repo add的私有仓库name和url后再次启动程序提示401，这里的授权配置需要在哪儿配置。
![8e280cba475c8bcf714967194b97e624](https://user-images.githubusercontent.com/88881577/184059414-9231594e-7ed9-4aec-88ef-ba5da60d0845.png)

启动程序加载公共镜像仓库配置如下：
![image](https://user-images.githubusercontent.com/88881577/184060077-5b33e712-1a2e-4b9a-bacf-30d47722982d.png)

本地直接helm install 私有镜像仓库配置和chart成功部署如下：
![image](https://user-images.githubusercontent.com/88881577/184060310-0ceca887-a2bf-4093-bf53-61d9d30def5c.png)

**Comment by opskumu** [comment]
@dnsisme 嗯嗯，那就是认证的问题导致的，支持认证的，以下字段的都支持，按照需求添加即可：

<img width="873" alt="image" src="https://user-images.githubusercontent.com/5445356/184062462-3a7852cb-2a23-4479-9ec6-97f15cefc248.png">

```
helmRepos:
  - name: <repo名>
    url: <repo地址>
    username: <username>
    password: <password>
```

**Comment by dnsisme** [comment]
@opskumu 感谢大佬支持解答，添加私有仓库认证配置后，程序启动成功。

我们计划将其以API形式暴露给前端，实现远程的自动化部署更新k8s服务，这个实现流程有大概介绍吗？

**Comment by opskumu** [comment]
@dnsisme 这个其实就是原生的 helm 封装的，因为 helm 本身不支持 API 调用，所以封装了一个，基本覆盖了 helm 命令的所有功能

**Comment by dnsisme** [comment]
![image](https://user-images.githubusercontent.com/88881577/184099775-cde53c0a-e14f-4009-9508-303f97afa686.png)

还有加认证在哪里添加呢
@opskumu

**Comment by opskumu** [comment]
@dnsisme 目前不支持认证哦，图中这个你是要删除 upload 目录中的 chart 吗？这个直接传 chart 的名字就可以了

**Comment by dnsisme** [comment]
@opskumu
截图是为了测试DEL /api/charts/upload/:chart接口功能是否符合预期，改成chart名称后删除成功，chart在helm-wrapper启动的server上存储，这里是从server所在的机器删除呢还是从helm repo仓库中删除chart包呢？

**Comment by dnsisme** [comment]
有helm list的接口吗？

**Comment by opskumu** [comment]
@dnsisme 只删除目录下的哈

**Comment by dnsisme** [comment]
好的 感谢大佬支持 这个issue可以关闭啦 我暂没问题 后续我会将镜像仓库更新成公网的地址 再去验证 顺带加一下认证
