### ISSUE TITLE
helm upgrade --install option not work

### ISSUE THREAD

**Issue by stupid-yu** [opskumu/helm-wrapper#74]
Hello, It's me again.
When using `--install` option, Helm-Wrapper doesn't work  as expected.
> `helm upgrade --install` （-i , --install           if a release by this name doesn't already exist, run an install）

Here is my test case:
`http://{{ip}}:{{port}}/api/namespaces/ns-cloud/releases/kfk?chart=helm/kafka`
body

```
{
    "install": true,
    "values": "http://{{ip}}:{{port}}/values.yaml"
}
```

response

```
{
	"code": 1,
	"error": "\"kfk\" has no deployed releases"
}
```

**Comment by opskumu** [comment]
@stupid-yu get

**Comment by opskumu** [comment]
>    // Setting this to `true` will NOT cause `Upgrade` to perform an install if the release does not exist.
>    // That process must be handled by creating an Install action directly. See cmd/upgrade.go for an
>    // example of how this flag is used.

I will fix this problem as soon.

**Comment by opskumu** [comment]
@stupid-yu now master branch  latest code already fix `--install`

**Comment by stupid-yu** [comment]
It works.:heart: Thanks again !
