### ISSUE TITLE
install with parameter set

### ISSUE THREAD

**Issue by szgRunner** [opskumu/helm-wrapper#76]
when i use parameter set ,i cannot change my manifest.so how should i pass this parameter?

**Comment by opskumu** [comment]
@szgRunner  you mean like this https://github.com/opskumu/helm-wrapper/issues/69?

**Comment by szgRunner** [comment]
i had read it ,but it did not work @opskumu

**Comment by szgRunner** [comment]
param set like #69 is right?

**Comment by opskumu** [comment]
@szgRunner  yes, like

```json
"set": [
    "ingress.annotations.kubernetes\\.io/ingress\\.class=traefik",
    "ingress.annotations.traefik\\.ingress\\.kubernetes\\.io/router\\.entrypoints=websecure"
]
```

**Comment by szgRunner** [comment]
my request like this 
curl -XPOST IP:PORT/api/namespace/iecas-redis/releases/redis-single?chart=local/redis -d '{"dry_run": false, "create_namespace": true, "atomic": true, "version": "10.7.17" , "set": ["global.redis.paassword=123456", "image.pullPolicy=Always"]}'

**Comment by opskumu** [comment]
@szgRunner here your set `.` no need escape character

``` json
{
    "set": [
        "global.redis.paassword=123456",
        "image.pullPolicy=Always"
    ]
}
```

**Comment by szgRunner** [comment]
@opskumu i already try it yesterday just like what you said,it has not work. but i tried it again just now, and it worked, so weird!
`{
    "set": [
        "global.redis.paassword=123456",
        "image.pullPolicy=Always"
    ]
}`

**Comment by szgRunner** [comment]
@opskumu when my request body use param "atomic": true, return error
like this : release redis-single failed , and has been uninstalled due to atomic being set: client rate limiter Wait returned an error: context deadline exceeded.
when use code line:
   `helm install --atomic `
no problem

**Comment by szgRunner** [comment]
> @szgRunner here your set `.` no need escape character `\`
> 
> ```json
> {
>     "set": [
>         "global.redis.paassword=123456",
>         "image.pullPolicy=Always"
>     ]
> }
> ```
> 
> `kubernetes.io/ingress.class` is a key so need escape like `kubernetes\\.io/ingress\\.class`.
> 
> @szgRunner 简单说哈，你的字段不需要用转义，实例里面有转义是因为那个是完整的一个单词哈，所以需要转义

your mean is when i want to change my nodeSelector or source label etc,  my key should be escaped , it is right?

**Comment by opskumu** [comment]
@szgRunner GET request with body

**Comment by szgRunner** [comment]
> GET request with body

why? POST is not allowed?

**Comment by opskumu** [comment]
@szgRunner because it's a `GET` Request ...

**Comment by szgRunner** [comment]
@opskumu but you have a body
