### ISSUE TITLE
通过上传 chart 接口，上传chart之后，部署应用，无法部署

### ISSUE THREAD

**Issue by 600849155** [opskumu/helm-wrapper#8]
通过上传 chart 接口，上传chart之后，部署应用，无法部署。
部署接口提示 ：cannot re-use a name that is still in use
查看日志：
<img width="989" alt="F03C7978-9893-49D3-BBEC-C6F0EC4ECD35" src="https://user-images.githubusercontent.com/20468753/90228873-9317a280-de49-11ea-9841-55cdcd53c865.png">

ps: 通过原生的 helm 命令 helm list -A 查看该命名空间是没有部署过该 chart 包的应用的

**Comment by opskumu** [comment]
https://github.com/helm/helm/issues/4174 看下这个 issue，应该是有 k8s 相关残留的资源没有清除吧，参考刚刚提到的 issue 用 kubectl 看看

**Comment by 600849155** [comment]
> [helm/helm#4174](https://github.com/helm/helm/issues/4174) 看下这个 issue，应该是有 k8s 相关残留的资源没有清除吧，参考刚刚提到的 issue 用 kubectl 看看
> 
> 这个上传的包如果用 helm 命令安装应该也会报类似错误的

整个 pods 都删掉重新启动也不行，用 helm install 命令启动是可以的

**Comment by opskumu** [comment]
上传的 charts 安装其实是使用的同样的接口安装的，只是安装的是本地的 charts，或者你试一下在一个新空间部署，helm 不仅仅是 pods 相关的，那个 issue 有说其它一些资源的，有可能是资源清理不干净导致的

**Comment by 600849155** [comment]
> 上传的 charts 安装其实是使用的同样的接口安装的，只是安装的是本地的 charts，或者你试一下在一个新空间部署，helm 不仅仅是 pods 相关的，那个 issue 有说其它一些资源的，有可能是资源清理不干净导致的

排查出问题了，我们部署 chart 包的 secret 有问题导致的， helm 的这个错误提示很奇怪，什么都提示这个
