### ISSUE TITLE
helm install 时候怎么指定 values.yaml呢

### ISSUE THREAD

**Issue by leon0204** [opskumu/helm-wrapper#83]
helm install 时候怎么指定 values.yaml呢 还是说只能通过 --set 添加上去

**Comment by opskumu** [comment]
@leon0204 是指 helm-wrapper 还是 helm install 本身啊，我理解你说的是 helm-wrapper 吧

**Comment by opskumu** [comment]
https://github.com/opskumu/helm-wrapper/issues/48 如果是 helm-wrapper 是通过 API 操作的

**Comment by leon0204** [comment]
<img width="867" alt="image" src="https://user-images.githubusercontent.com/13375688/233252601-3435aa24-f619-4cf5-bf11-affcb2687f72.png">

**Comment by leon0204** [comment]
helm install 中的 

  
    "values": "",               // `--values`
    "set": [],                  // `--set`
    
    能否支持设置 values.yaml路径的参数？
    
    就是怎么通过 install api 实现 
    
     helm install mysql-8 bitnami/mysql --set auth.rootPassword=Qqq123   -f values.yaml

**Comment by opskumu** [comment]
@leon0204 你们还有这个需求吗，这样的话直接用 helm 就可以了吧

**Comment by opskumu** [comment]
我想想看哈

**Comment by leon0204** [comment]
无法通过 install API  添加
--set auth.rootPassword=Qqq123  
 -f values.yaml  
 这两种参数吗  
 
 
 自定义配置参数嘛，应该挺常见吧。

**Comment by opskumu** [comment]
values 和 set 本身都是支持的，不过 values 是通过 body 中传值的方式来做的，因为是 API 调用

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/5445356/233253620-b3af05f8-d196-40ab-b451-e3be539a11fc.png">

**Comment by opskumu** [comment]
你说的这些都是支持的，放在 body 里面就可以了

{
    "values": "xxx",
    "set":  [],
    "set_string": []
}

**Comment by opskumu** [comment]
<img width="839" alt="image" src="https://user-images.githubusercontent.com/5445356/233253957-ee5a8547-3175-4e29-a30a-c4135aaa73fd.png">

README  里面有详细介绍的

**Comment by opskumu** [comment]
至于调用 API 的时候 values 支持指定文件这个是没有做的

**Comment by leon0204** [comment]
> <img alt="image" width="867" src="https://user-images.githubusercontent.com/13375688/233252601-3435aa24-f619-4cf5-bf11-affcb2687f72.png">

@opskumu 这个set 应该怎么传呢   --set auth.rootPassword=Qqq123  报错了

**Comment by opskumu** [comment]
@leon0204 放在 body 里面

**Comment by leon0204** [comment]
截图放在body里啦

**Comment by leon0204** [comment]
可以
