### ISSUE TITLE
多集群传参

### ISSUE THREAD

**Issue by zhang-zzq** [opskumu/helm-wrapper#92]
请问多集群怎么传参
<img width="1032" alt="image" src="https://github.com/opskumu/helm-wrapper/assets/71244419/2bb53658-7c1d-4e11-ad1c-c94fe0fde34a">
![image](https://github.com/opskumu/helm-wrapper/assets/71244419/3b2f81b1-9052-4580-bd48-d8702f83d658)

**Comment by opskumu** [comment]
指定绝对路径

**Comment by zhang-zzq** [comment]
> 指定绝对路径

绝对路径可以成功，谢谢

**Comment by zhang-zzq** [comment]
请问可以通过 `https://ip:6443 + token` 的方式请求吗

**Comment by opskumu** [comment]
这块功能没有支持哦，依赖 kubeconfig

**Comment by zhang-zzq** [comment]
> 这块功能没有支持哦，依赖 kubeconfig

好吧。不过k8s本身也支持通过token生成kubeconfig文件，也可以变相实现通过`https://ip:6443 + token`请求
```
kubectl config set-cluster kubernetes-test --server=https://ip:6443 --kubeconfig=/opt/kubeconfig/config-test
kubectl config set-credentials kubernetes-admin --token="eyJxxx" --kubeconfig=/opt/kubeconfig/config-test
```

**Comment by zhang-zzq** [comment]
`listReleases`中有all_namespaces的参数后，指定的kube_config好像会失效
```
{
    "all_namespaces": true
}
```

**Comment by opskumu** [comment]
> > 这块功能没有支持哦，依赖 kubeconfig
> 
> 好吧。不过k8s本身也支持通过token生成kubeconfig文件，也可以变相实现通过`https://ip:6443 + token`请求
> 
> ```
> kubectl config set-cluster kubernetes-test --server=https://ip:6443 --kubeconfig=/opt/kubeconfig/config-test
> kubectl config set-credentials kubernetes-admin --token="eyJxxx" --kubeconfig=/opt/kubeconfig/config-test
> ...
> ```

主要是结合 helm 这块来做的哈

**Comment by zhang-zzq** [comment]
> 

嗯呢，我自己实现下这块

**Comment by zhang-zzq** [comment]
> > `listReleases`中有all_namespaces的参数后，指定的kube_config好像会失效
> > ```
> > {
> >     "all_namespaces": true
> > }
> > ```
> 
> 这个确实有这个问题，稍等一下，我修复下，大概知道什么原因了

感谢

**Comment by opskumu** [comment]
@zhang-zzq all_namespaces 的 bug 已经修复了，多谢反馈
